version: "3"
services:
  db:
    image: sqlDockerTest
    build:
      context: ./SQLServer
      dockerfile: dockerfile
    ports:
      - "1450:1433"
    volumes:
      - "sqlvolume:/var/opt/mssql"
volumes:
  sqlvolume:
